### PR TITLE
Add service provider and facade tests.

### PR DESCRIPTION
**Pull request by vinkla**
Also imported Illuminates `ServiceProvider` class instead of Orchestras.

### CODE REVIEW

**Comment by jbrooksuk** [comment]
Can you apply the patch file as per https://styleci.io/commits/35d7c27a7e804e3611d6b15961f60ff6095296f6 please. Then squash down your commits and we'll merge it.

**Comment by vinkla** [comment]
I didn't get what was wrong with it? Should there be an extra blank line?

**Comment by jbrooksuk** [comment]
I can merge and fix for you if you'd like?

**Comment by vinkla** [comment]
No I can do it, if its okay. I want to learn :) It wants me to rename `Tests` to `tests`?

**Comment by jbrooksuk** [comment]
Awesome!

Yeah, because the folder name is lowercase. @GrahamCampbell what's the deal here?

**Comment by GrahamCampbell** [comment]
We need the namespace to be `NotifyMeHQ\Tests\Laravel5`, then we're sorted.

**Comment by vinkla** [comment]
Done.

**Comment by vinkla** [comment]
Thank you!

**Comment by jbrooksuk** [comment]
No, thank you! :)

**Pull request merged**
